### ISSUE TITLE
Tests fail with missing ref data

### ISSUE THREAD

**Issue by ialarmedalien** [kbaseapps/kb_blast#44]
Running `kb-sdk test` gives the following error:

```

> Traceback (most recent call last):
>    File "/kb/module/lib/kb_blast/Utils/BlastUtil.py", line 375, in write_target_obj_to_file
>     objects = self.wsClient.get_objects2({'objects':[{'ref': input_many_ref}]})['data']
>    File "/kb/module/lib/installed_clients/WorkspaceClient.py", line 1951, in get_objects2
>      [params], self._service_ver, context)
>    File "/kb/module/lib/installed_clients/baseclient.py", line 282, in call_method
>      return self._call(url, service_method, args, context)
>    File "/kb/module/lib/installed_clients/baseclient.py", line 187, in _call
>     raise ServerError(**err['error'])
> installed_clients.baseclient.ServerError: JSONRPCError: -32500. No object with name GCF_001566335.1 exists in workspace 19516 (name ReferenceDataManager)
> us.kbase.workspace.database.exceptions.NoSuchObjectException: No object with name GCF_001566335.1 exists in workspace 19516 (name ReferenceDataManager)
```

See [this GitHub action](https://github.com/ialarmedalien/kb_blast/runs/517182703?check_suite_focus=true) for the full test output.

**Comment by dcchivian** [comment]
are you running against APPDEV?  That data is in the public workspace only on CI and PROD

**Comment by ialarmedalien** [comment]
Aha - that is the source of the problem! In that case, there should be a workspace set up on appdev for running these tests against.

**Comment by dcchivian** [comment]
I wholeheartedly agree!  but time...

**Comment by dcchivian** [comment]
changing unit tests to upload data at runtime
